/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_biosino_util_jni_JETreat */

#ifndef _Included_org_biosino_util_jni_JETreat
#define _Included_org_biosino_util_jni_JETreat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_biosino_util_jni_JETreat
 * Method:    doJointEntropyTreat
 * Signature: (DILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_biosino_util_jni_JETreat_doJointEntropyTreat
  (JNIEnv *, jclass, jdouble, jint, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
